GET http://localhost:3000/players/

### 

POST http://localhost:3000/players/
Content-Type: application/json

{
  "player_name": "Vishal",
  "jersey_number": 17,
  "role": "Bowler"
}

###

GET http://localhost:3000/players/21/

###

PUT http://localhost:3000/players/26/
Content-Type: application/json

{
  "player_name": "kiran",
  "jersey_number": 57,
  "role": "Bowler"
}

###
DELETE http://localhost:3000/players/21/
